development:
  adapter: postgresql
  encoding: utf8
  database: xamsa_development
  pool: 5
  username: postgres
  host: localhost
  template: template0

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
